/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProtoRandomNFT,
  IProtoRandomNFTInterface,
} from "../../../contracts/interfaces/IProtoRandomNFT";

const _abi = [
  {
    inputs: [],
    name: "getChanceArray",
    outputs: [
      {
        internalType: "uint256[3]",
        name: "",
        type: "uint256[3]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getInitialized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getNftTokenUris",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "moddedRng",
        type: "uint256",
      },
    ],
    name: "getPropsFromModdedRng",
    outputs: [
      {
        internalType: "enum IProtoRandomNFT.Props",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenCounter",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requestNft",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProtoRandomNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IProtoRandomNFTInterface {
    return new Interface(_abi) as IProtoRandomNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProtoRandomNFT {
    return new Contract(address, _abi, runner) as unknown as IProtoRandomNFT;
  }
}
