/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as randomNftProtoSol from "./RandomNFTProto.sol";
export type { randomNftProtoSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { VRFv2Consumer } from "./VRFv2Consumer";
